20260323-v1 Updates
ALL
- Bump package dependency versions

root
- Modify husky hooks

Signed-off-by: Lindjunne Gerard Montenegro II <lgbmontenegroii@4thdevision.tech>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -7,17 +7,35 @@ echo ==============================
 echo
 
 # Create a list of non-deleted staged files
-stagedFiles=$( git diff --name-only --diff-filter=d --staged )
+stagedFiles=$(git diff --name-only --diff-filter=d --staged)
 
 if [ -n "$stagedFiles" ]; then
+    echo 'Linting and formatting staged files...'
+
     # Use ESLint to do syntax checking of staged files
-    echo 'Linting code with ESLint...'
-    echo -e $stagedFiles | xargs -n 10 pnpm eslint --no-warn-ignored --no-error-on-unmatched-pattern
+    echo "$stagedFiles" | xargs -n 50 ./node_modules/.bin/eslint --no-warn-ignored --no-error-on-unmatched-pattern &
+    ESLINT_PID=$!
 
     # Use prettier to format code style of staged files
-    echo 'Formatting staged files with Prettier...'
-    echo -e $stagedFiles | xargs -n 10 pnpm prettier --write --ignore-unknown --no-error-on-unmatched-pattern
-    echo -e $stagedFiles | xargs -n 10 git add
+    echo "$stagedFiles" | xargs -n 50 ./node_modules/.bin/prettier --write --ignore-unknown --no-error-on-unmatched-pattern &
+    PRETTIER_PID=$!
+
+    wait $ESLINT_PID
+    ESLINT_EXIT=$?
+
+    wait $PRETTIER_PID
+    PRETTIER_EXIT=$?
+
+    # Re-stage any files reformatted by Prettier
+    if [ $PRETTIER_EXIT -eq 0 ]; then
+        echo "$stagedFiles" | xargs -n 50 git add
+    fi
+
+    # Abort commit if ESLint found errors
+    if [ $ESLINT_EXIT -ne 0 ]; then
+        echo 'ESLint found errors. Commit aborted.'
+        exit 1
+    fi
 fi
 
 echo
@@ -25,3 +43,5 @@ echo ============================
 echo = END: git pre-commit hook =
 echo ============================
 echo
+
+exit 0
